import { serve } from "https://deno.land/std@0.140.0/http/server.ts";

const API_KEY = Deno.env.get("YOUTUBE_API_KEY"); // Secure API key
const cache = new Map<string, any>(); // In-memory cache

// Function to fetch captions from YouTube API
async function fetchCaptions(videoId: string) {
  const cacheKey = `captions-${videoId}`;
  if (cache.has(cacheKey)) {
    console.log("📌 Serving from cache:", videoId);
    return cache.get(cacheKey);
  }

  const url = `https://www.googleapis.com/youtube/v3/captions?videoId=${videoId}&key=${API_KEY}&part=snippet`;

  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`YouTube API Error: ${response.status}`);

    const data = await response.json();
    cache.set(cacheKey, data); // Store response in cache
    return data;
  } catch (error) {
    console.error("❌ Error fetching captions:", error);
    throw error;
  }
}

// Function to fetch transcript using captions ID
async function fetchTranscript(captionId: string) {
  const cacheKey = `transcript-${captionId}`;
  if (cache.has(cacheKey)) {
    console.log("📌 Serving transcript from cache:", captionId);
    return cache.get(cacheKey);
  }

  const url = `https://www.googleapis.com/youtube/v3/captions/${captionId}?key=${API_KEY}`;
  
  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`YouTube API Error: ${response.status}`);

    const data = await response.text();
    cache.set(cacheKey, data); // Store transcript in cache
    return data;
  } catch (error) {
    console.error("❌ Error fetching transcript:", error);
    throw error;
  }
}

// Main API handler
async function handler(req: Request): Promise<Response> {
  if (req.method === "OPTIONS") {
    return new Response(null, {
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "POST, OPTIONS",
        "Access-Control-Allow-Headers": "Content-Type",
      },
    });
  }

  if (req.method !== "POST") {
    return new Response("❌ Method Not Allowed", { status: 405 });
  }

  try {
    const { videoId } = await req.json();
    if (!videoId) return new Response("❌ Missing videoId", { status: 400 });

    console.log("📥 Fetching captions for video:", videoId);
    const captionData = await fetchCaptions(videoId);

    if (!captionData.items?.length) {
      return new Response(JSON.stringify({ message: "❌ No captions available" }), {
        status: 404,
        headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
      });
    }

    // Extract captions
    const captions = captionData.items.map((item: any) => ({
      id: item.id,
      language: item.snippet.language,
      autoGenerated: item.snippet.trackKind === "ASR",
    }));

    // If a valid caption exists, fetch transcript
    let transcript = "";
    if (captions.length > 0) {
      console.log("📥 Fetching transcript for:", captions[0].id);
      transcript = await fetchTranscript(captions[0].id);
    }

    return new Response(JSON.stringify({ captions, transcript }), {
      headers: { "Content-Type": "application/json", "Access-Control-Allow-Origin": "*" },
    });
  } catch (error) {
    console.error("❌ Error processing request:", error);
    return new Response(`❌ Internal Server Error: ${error.message}`, { status: 500 });
  }
}

serve(handler);
