
import React, { useState, useRef } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import KnowledgeGraph from "@/components/KnowledgeGraph";
import { Loader2, ExternalLink, Youtube, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { 
  fetchYoutubeTranscription, 
  fetchYoutubeCaptions, 
  fetchYoutubeApiCaptions, 
  fetchGeminiTranscription,
  analyzeTranscription 
} from "@/services/youtubeService";
import { FormattedHistoricalEntity } from "@/types/supabase";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { supabase } from "@/integrations/supabase/client";

const YouTubeAnalysis = () => {
  // States for the YouTube video and analysis
  const [url, setUrl] = useState<string>("");
  const [videoId, setVideoId] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [analyzing, setAnalyzing] = useState<boolean>(false);
  const [transcription, setTranscription] = useState<string>("");
  const [entities, setEntities] = useState<FormattedHistoricalEntity[]>([]);
  const [activeTab, setActiveTab] = useState<"video" | "transcription" | "visualization">("video");
  const [error, setError] = useState<string | null>(null);
  const [transcriptionMethod, setTranscriptionMethod] = useState<"standard" | "alternative" | "api" | "gemini">("standard");
  const videoContainerRef = useRef<HTMLDivElement>(null);

  // Function to extract video ID from YouTube URL
  const extractVideoId = (url: string): string | null => {
    const regExp = /^.*(youtu.be\/|v\/|e\/|u\/\w+\/|embed\/|v=)([^#&?]*).*/;
    const match = url.match(regExp);
    return match && match[2].length === 11 ? match[2] : null;
  };

  // Handle URL submission
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    const id = extractVideoId(url);
    if (id) {
      setVideoId(id);
      setTranscription("");
      setEntities([]);
      setActiveTab("video");
      setTranscriptionMethod("standard");
      toast.success("YouTube video loaded successfully");
    } else {
      toast.error("Invalid YouTube URL");
      setError("Please enter a valid YouTube URL (e.g., https://www.youtube.com/watch?v=...)");
    }
  };

  // Fetch transcription from YouTube video
  const fetchTranscription = async () => {
    if (!videoId) return;
    
    setLoading(true);
    setError(null);
    try {
      console.log(`Fetching transcription for video ID: ${videoId}`);
      console.log(`Using ${transcriptionMethod} method`);
      
      let transcriptionText = "";
      
      switch (transcriptionMethod) {
        case "gemini":
          try {
            transcriptionText = await fetchGeminiTranscription(videoId);
          } catch (error) {
            console.error("Gemini method failed:", error);
            throw error;
          }
          break;
          
        case "api":
          try {
            console.log("Using API captions method");
            const { data, error } = await supabase.functions.invoke("get-youtube-api-captions", {
              body: { videoId }
            });
            
            if (error) throw new Error(`Function error: ${error.message}`);
            
            console.log("Received captions data:", data);
            
            if (data && data.captions && data.captions.length > 0) {
              // For now, just display the captions info since we don't get full transcript
              transcriptionText = `Available caption tracks:\n\n${
                data.captions.map((caption: any) => 
                  `- ${caption.name} (${caption.language})${caption.isAutoGenerated ? ' (Auto-generated)' : ''}`
                ).join('\n')
              }`;
            } else {
              throw new Error("No captions found for this video");
            }
          } catch (apiError) {
            console.error("API captions method failed:", apiError);
            throw apiError;
          }
          break;
          
        case "alternative":
          // Use the alternative captions endpoint
          transcriptionText = await fetchYoutubeCaptions(videoId);
          break;
          
        case "standard":
        default:
          // Use the original transcription endpoint
          try {
            transcriptionText = await fetchYoutubeTranscription(videoId);
          } catch (mainError) {
            console.error("Error with main method, trying fallback:", mainError);
            setTranscriptionMethod("alternative");
            toast.info("Trying alternative method to fetch captions...");
            try {
              transcriptionText = await fetchYoutubeCaptions(videoId);
            } catch (fallbackError) {
              console.error("Fallback method also failed, trying Gemini:", fallbackError);
              setTranscriptionMethod("gemini");
              toast.info("Trying Gemini AI to extract transcription...");
              try {
                transcriptionText = await fetchGeminiTranscription(videoId);
              } catch (geminiError) {
                console.error("Gemini method also failed, trying API captions:", geminiError);
                setTranscriptionMethod("api");
                toast.info("Trying API captions method as last resort...");
                
                const { data, error } = await supabase.functions.invoke("get-youtube-api-captions", {
                  body: { videoId }
                });
                
                if (error) throw new Error(`Function error: ${error.message}`);
                
                if (data && data.captions && data.captions.length > 0) {
                  // For now, just display the captions info since we don't get full transcript
                  transcriptionText = `Available caption tracks:\n\n${
                    data.captions.map((caption: any) => 
                      `- ${caption.name} (${caption.language})${caption.isAutoGenerated ? ' (Auto-generated)' : ''}`
                    ).join('\n')
                  }`;
                } else {
                  throw new Error("No captions found for this video");
                }
              }
            }
          }
          break;
      }
      
      setTranscription(transcriptionText);
      setActiveTab("transcription");
      toast.success("Transcription fetched successfully");
    } catch (error) {
      console.error("Error fetching transcription:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      setError(`Failed to fetch transcription: ${errorMessage}. Please try another method or video.`);
      toast.error("Failed to fetch transcription: " + errorMessage);
    } finally {
      setLoading(false);
    }
  };

  // Toggle between transcription methods
  const toggleTranscriptionMethod = () => {
    const methods = ["standard", "alternative", "gemini", "api"] as const;
    const currentIndex = methods.indexOf(transcriptionMethod);
    const nextIndex = (currentIndex + 1) % methods.length;
    const newMethod = methods[nextIndex];
    
    setTranscriptionMethod(newMethod);
    toast.info(`Using ${newMethod} transcription method`);
  };

  // Analyze transcription to extract historical entities
  const handleAnalyzeTranscription = async () => {
    if (!transcription) {
      toast.error("No transcription to analyze");
      return;
    }
    
    setAnalyzing(true);
    setError(null);
    try {
      console.log(`Analyzing transcription of length: ${transcription.length}`);
      const extractedEntities = await analyzeTranscription(transcription);
      
      if (extractedEntities.length > 0) {
        setEntities(extractedEntities);
        setActiveTab("visualization");
        toast.success(`Analysis complete: ${extractedEntities.length} entities found`);
      } else {
        toast.warning("No significant entities found in the transcription");
        setError("No significant historical entities were found in this transcription.");
      }
    } catch (error) {
      console.error("Error analyzing transcription:", error);
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      setError(`Failed to analyze transcription: ${errorMessage}`);
      toast.error("Failed to analyze transcription: " + errorMessage);
    } finally {
      setAnalyzing(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <h1 className="text-3xl font-bold mb-6 text-white">YouTube Video Analysis</h1>
      
      {/* Error Display */}
      {error && (
        <Alert variant="destructive" className="mb-4">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}
      
      {/* URL Input Form */}
      <form onSubmit={handleSubmit} className="mb-6 flex gap-2">
        <Input
          type="url"
          value={url}
          onChange={(e) => setUrl(e.target.value)}
          placeholder="Enter YouTube URL (e.g., https://www.youtube.com/watch?v=...)"
          className="flex-1"
          required
        />
        <Button type="submit" disabled={!url}>Load Video</Button>
      </form>
      
      {/* Tabs for Video, Transcription, and Visualization */}
      {videoId && (
        <Tabs value={activeTab} onValueChange={(value) => setActiveTab(value as any)} className="space-y-4">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="video">Video</TabsTrigger>
            <TabsTrigger value="transcription">Transcription</TabsTrigger>
            <TabsTrigger value="visualization">Visualization</TabsTrigger>
          </TabsList>
          
          {/* Video Tab */}
          <TabsContent value="video" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Youtube className="h-5 w-5" /> YouTube Video
                </CardTitle>
                <CardDescription>
                  Watch the video and then fetch its transcription for analysis
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div ref={videoContainerRef} className="relative aspect-video w-full overflow-hidden rounded-md">
                  <iframe
                    src={`https://www.youtube.com/embed/${videoId}`}
                    title="YouTube video player"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                    allowFullScreen
                    className="absolute top-0 left-0 w-full h-full"
                  ></iframe>
                </div>
              </CardContent>
              <CardFooter className="flex justify-between flex-wrap gap-2">
                <div className="flex gap-2">
                  <Button 
                    variant="outline" 
                    onClick={() => window.open(`https://www.youtube.com/watch?v=${videoId}`, '_blank')}
                  >
                    Open in YouTube <ExternalLink className="ml-2 h-4 w-4" />
                  </Button>
                  <Button 
                    variant="outline" 
                    onClick={toggleTranscriptionMethod}
                  >
                    {`Using ${transcriptionMethod} method`}
                  </Button>
                </div>
                <Button 
                  onClick={fetchTranscription} 
                  disabled={loading}
                >
                  {loading ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Fetching...
                    </>
                  ) : (
                    "Fetch Transcription"
                  )}
                </Button>
              </CardFooter>
            </Card>
          </TabsContent>
          
          {/* Transcription Tab */}
          <TabsContent value="transcription" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>Video Transcription</CardTitle>
                <CardDescription>
                  Review the transcription and analyze it to extract knowledge entities
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="mb-2 text-sm text-muted-foreground">
                  Fetched using the <span className="font-semibold">{transcriptionMethod}</span> method
                </div>
                <Textarea 
                  value={transcription} 
                  onChange={(e) => setTranscription(e.target.value)}
                  placeholder="Transcription will appear here..."
                  className="min-h-[300px] font-mono text-sm"
                />
              </CardContent>
              <CardFooter>
                <Button 
                  onClick={handleAnalyzeTranscription} 
                  disabled={!transcription || analyzing} 
                  className="ml-auto"
                >
                  {analyzing ? (
                    <>
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      Analyzing...
                    </>
                  ) : (
                    "Analyze Transcription"
                  )}
                </Button>
              </CardFooter>
            </Card>
          </TabsContent>
          
          {/* Visualization Tab */}
          <TabsContent value="visualization" className="space-y-4">
            <Card>
              <CardHeader>
                <CardTitle>Knowledge Graph</CardTitle>
                <CardDescription>
                  Visual representation of entities and connections from the video
                </CardDescription>
              </CardHeader>
              <CardContent className="min-h-[600px] relative">
                {entities.length > 0 ? (
                  <KnowledgeGraph 
                    entities={entities} 
                    onEntitySelect={(entity) => {
                      toast.info(`Selected: ${entity.name}`);
                    }} 
                  />
                ) : (
                  <div className="flex flex-col items-center justify-center h-[500px] text-muted-foreground">
                    <p>No visualization data available yet.</p>
                    <p className="text-sm mt-2">Analyze the transcription to generate a knowledge graph.</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}
      
      {/* Initial state when no video is loaded */}
      {!videoId && (
        <Card className="mt-6">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <Youtube className="h-16 w-16 text-muted-foreground mb-4" />
            <h3 className="text-xl font-semibold mb-2">No Video Loaded</h3>
            <p className="text-muted-foreground text-center max-w-md">
              Enter a YouTube URL above to start. The tool will extract the transcription
              and analyze it to create a knowledge graph of concepts and relationships.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default YouTubeAnalysis;
