import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const API_KEY = Deno.env.get("YOUTUBE_API_KEY"); // Secure API key
const API_URL = "https://www.googleapis.com/youtube/v3/captions";
const cache = new Map(); // Simple in-memory cache

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders, status: 204 });
  }
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  try {
    const { videoId } = await req.json();
    if (!videoId) {
      return new Response(JSON.stringify({ error: "Video ID is required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Check cache
    if (cache.has(videoId)) {
      return new Response(JSON.stringify(cache.get(videoId)), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    console.log(`Fetching captions for video ID: ${videoId}`);
    const response = await fetch(`${API_URL}?videoId=${videoId}&key=${API_KEY}&part=snippet`);
    
    if (!response.ok) {
      const errorBody = await response.text(); // Get the response body for more details
      throw new Error(`YouTube API error: ${response.statusText} - ${errorBody}`);
    }

    const data = await response.json();
    if (!data.items || data.items.length === 0) {
      return new Response(JSON.stringify({ error: "No captions found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Extract only English captions
    const captions = data.items
      .filter((item: any) => item.snippet.language === "en")
      .map((item: any) => ({
        id: item.id,
        name: item.snippet.name || "Unknown",
        isAutoGenerated: item.snippet.trackKind === "ASR",
      }));

    if (captions.length === 0) {
      return new Response(JSON.stringify({ error: "No English captions found" }), {
        status: 404,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Store in cache
    cache.set(videoId, captions);

    return new Response(JSON.stringify({ captions }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error("Error:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
